# Generated by Django 2.0.1 on 2018-01-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=50)),
                ('api_call_time', models.DateTimeField(verbose_name='called at')),
            ],
        ),
    ]
